version: '3'
services:
  client:
    image: node:14-alpine
    ports:
      - 3000:3000
    networks:
      - pokemon-app
    volumes:
      - ./pokemon-client:/app
    working_dir: /app
    command: npm start
    # links:
    #   - 'server:server'
  server:
    image: node:14-alpine
    ports:
      - 5000:5000
    networks:
      - pokemon-app
    volumes:
      - ./pokemon-server:/app
    working_dir: /app
    command: npm run server
    links:
      - 'mongo:data'
  mongo:
    image: mongo
    ports:
      - 28017:27017
    networks:
      - pokemon-app
    
networks:
  pokemon-app:
    driver: bridge #default: allows talk to one another 

